[package]
name = "av_engine"
version = "0.2.0"
edition = "2024"

[dependencies]
tonic = "0.14.2"
prost = "0.14.1"
tonic-prost = "0.14.2"
anyhow.workspace = true

av_core = { path = "../av_core" }  # assuming workspace linkage

[build-dependencies]
tonic-prost-build  = "0.14.2"
